### ISSUE TITLE
Проблемная ситуация и обоснование необходимости разработки

### ISSUE THREAD

**Issue by earring** [earring/testgenerator#8]
Проанализировать проблемную ситуацию в предметной области, определить позицию разрабатываемого ПО.

**Comment by AlexRub** [comment]
Что значит определить позицию?

**Comment by earring** [comment]
Да. Это значит, что надо написать в отчете проблемную ситуацию и т.д. Позиция - как я понял, это каким образом приложение решает проблемную ситуацию. Типа положение его в проблеме.
